# Uncomment the next line to define a global platform for your project
platform :ios, '17.6'

target 'CredPlatformContest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CredPlatformContest
  pod 'Apollo', '0.30.0'

  target 'CredPlatformContestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CredPlatformContestUITests' do
    # Pods for testing
  end

end
