name: CredPlatform iOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-latest
    steps:
      - name: Check Xcode version
        run: xcodebuild -showsdks
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd CredPlatformContest
          pod install

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v3
        with:
          xcode-version: '16.2'

      - name: Build and Test
        run: |
          cd CredPlatformContest
          xcodebuild clean build test \
            -workspace CredPlatformContest.xcworkspace \
            -scheme CredPlatformContest \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            CODE_SIGNING_ALLOWED=NO
